<a href="https://colab.research.google.com/github/al-foysal-tuhin/ostad_ai_engineering_course/blob/main/Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ASSIGNMENT**

In [ ]:
import numpy as np
import pandas as pd

# Part 1: NumPy – Numerical Computing

**Task 1: Array Creation and Operations**

A 1D array of integers from 0 to 20.

In [ ]:
arr = np.arange(1, 21)
print("1D Array:", arr)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


A 2D array of shape (4, 5) filled with random integers from 10 to 99.

In [ ]:
arr_2d = np.random.randint(10,100, size=(4,5))
print("2D Array:\n", arr_2d)

2D Array:
 [[53 44 76 87 22]
 [37 96 45 92 52]
 [50 17 95 84 78]
 [95 39 70 76 59]]


A 3x3 identity matrix.

In [ ]:
identity_matrix = np.eye(3)
print("3× Identity Matrix:\n", identity_matrix)

3× Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***2. Perform the following operations:***

Find the mean, median, and standard deviation of the 2D array.

In [ ]:
mean_val = np.mean(arr_2d)
median_val = np.median(arr_2d)
std_dev = np.std(arr_2d)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)

Mean: 63.35
Median: 64.5
Standard Deviation: 24.23277738931301


Slice and print the second row and third column of the 2D array.

In [ ]:
second_row = arr_2d[1]
print("\nSecond Row:", second_row)

third_column = arr_2d[:, 2]
print("\nThird Column:", third_column)


Second Row: [37 96 45 92 52]

Third Column: [76 45 95 70]


Multiply two arrays element-wise.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = arr1 * arr2
print("Element-wise Multiplication:\n", result)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


**Task 2: Broadcasting and Reshaping**

Reshape a 1D array of size 16 into a 4x4 matrix.

In [ ]:
array_1d = np.arange(16)
matrix_2d = array_1d.reshape(4, 4)

print(matrix_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Add a 1D array [1, 2, 3, 4] to each row of the matrix using broadcasting.

In [ ]:
matrix = np.arange(16).reshape(4, 4)
array_1d = np.array([1, 2, 3, 4])

result = matrix + array_1d
print(result)

[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]
 [13 15 17 19]]


Flatten the matrix back to a 1D array.


In [ ]:
flattened_matrix= result.flatten()
print(flattened_matrix)

[ 1  3  5  7  5  7  9 11  9 11 13 15 13 15 17 19]


# Part 2: Pandas – Data Manipulation

**Task 3: Working with DataFrames**

Create a DataFrame with the following data:

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan'],
    'Age': [25, 30, 28, 35, 40],
    'Department': ['IT', 'HR', 'IT', 'Marketing', 'HR'],
    'Salary': [50000, 45000, 72000, 58000, 60000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age Department  Salary
0    Alice   25         IT   50000
1      Bob   30         HR   45000
2  Charlie   28         IT   72000
3    Diana   35  Marketing   58000
4     Evan   40         HR   60000


Perform these operations:

*   Add a new column Bonus = 10% of Salary.
*   Filter and display employees in the HR department.
*  Calculate average salary by department.
*  Save the DataFrame to a CSV file.

In [ ]:
df_new = df.assign(
    Bonus = df["Salary"] * 1.10
)
print(df_new)


      Name  Age Department  Salary    Bonus
0    Alice   25         IT   50000  55000.0
1      Bob   30         HR   45000  49500.0
2  Charlie   28         IT   72000  79200.0
3    Diana   35  Marketing   58000  63800.0
4     Evan   40         HR   60000  66000.0


In [ ]:
print(df[df["Department"] == "HR"])

   Name  Age Department  Salary
1   Bob   30         HR   45000
4  Evan   40         HR   60000


In [ ]:
avg_salary = df.groupby("Department")["Salary"].mean()
print(avg_salary)

Department
HR           52500.0
IT           61000.0
Marketing    58000.0
Name: Salary, dtype: float64


In [ ]:
dataset = df_new.to_csv("df_new.csv")

**Task 4: Data Cleaning & Analysis**

Use any public CSV dataset (e.g., from Kaggle or UCI ML Repository)
Load the dataset using pandas.read_csv()


Show:


* First 5 and last 5 rows
* Shape of dataset
* Columns and their data types
* Handle missing values (e.g., fill, drop)
* Generate basic statistics using .describe()

In [ ]:
df = pd.read_csv('BMW sales data (2010-2024) (1).csv')

In [ ]:
df.head()

Model  Year         Region  Color Fuel_Type Transmission  Engine_Size_L  \
0  5 Series  2016           Asia    Red    Petrol       Manual            3.5   
1        i8  2013  North America    Red    Hybrid    Automatic            1.6   
2  5 Series  2022  North America   Blue    Petrol    Automatic            4.5   
3        X3  2024    Middle East   Blue    Petrol    Automatic            1.7   
4  7 Series  2020  South America  Black    Diesel       Manual            2.1   

   Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0      151748      98740          8300                 High  
1      121671      79219          3428                  Low  
2       10991     113265          6994                  Low  
3       27255      60971          4047                  Low  
4      122131      49898          3080                  Low

In [ ]:
df.tail()

Model  Year         Region   Color Fuel_Type Transmission  \
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49997  5 Series  2010    Middle East     Red    Petrol    Automatic   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
49995            4.6      151030      42932          8182                 High  
49996            4.2      147396      48714          9816                 High  
49997            4.5      174939      46126          8280                 High  
49998            3.8        3379      58566          9486                 High  
49999            3.3      171003      77492          1764                  Low

In [ ]:
print(df.shape)

(50000, 11)


In [ ]:
print(df.isnull().sum())

Model                   0
Year                    0
Region                  0
Color                   0
Fuel_Type               0
Transmission            0
Engine_Size_L           0
Mileage_KM              0
Price_USD               0
Sales_Volume            0
Sales_Classification    0
dtype: int64


I simply had no Idea it would turn out to be an empty missing values dataset, Sorry Boss. Did something which was relevant

In [ ]:
mean = df['Price_USD'].mean()
df['Price_USD'] = df['Price_USD'].fillna(mean)

In [ ]:
print(mean)

75034.6009


In [ ]:
df_new = df.drop(columns = ['Mileage_KM', 'Year'])
print(df_new)

          Model         Region   Color Fuel_Type Transmission  Engine_Size_L  \
0      5 Series           Asia     Red    Petrol       Manual            3.5   
1            i8  North America     Red    Hybrid    Automatic            1.6   
2      5 Series  North America    Blue    Petrol    Automatic            4.5   
3            X3    Middle East    Blue    Petrol    Automatic            1.7   
4      7 Series  South America   Black    Diesel       Manual            2.1   
...         ...            ...     ...       ...          ...            ...   
49995        i3           Asia     Red    Hybrid       Manual            4.6   
49996        i3    Middle East  Silver  Electric       Manual            4.2   
49997  5 Series    Middle East     Red    Petrol    Automatic            4.5   
49998        i3           Asia   White  Electric    Automatic            3.8   
49999        X1  North America    Blue    Diesel       Manual            3.3   

       Price_USD  Sales_Volume Sales_Cl

In [ ]:
x3_data = df[df['Model'] == 'X3']
sales_by_region = x3_data.groupby('Region')['Sales_Volume'].sum()
print(sales_by_region)

Region
Africa           3742723
Asia             3796115
Europe           3705572
Middle East      3745004
North America    4056192
South America    3699923
Name: Sales_Volume, dtype: int64


In [ ]:
print(df.describe)

<bound method NDFrame.describe of           Model  Year         Region   Color Fuel_Type Transmission  \
0      5 Series  2016           Asia     Red    Petrol       Manual   
1            i8  2013  North America     Red    Hybrid    Automatic   
2      5 Series  2022  North America    Blue    Petrol    Automatic   
3            X3  2024    Middle East    Blue    Petrol    Automatic   
4      7 Series  2020  South America   Black    Diesel       Manual   
...         ...   ...            ...     ...       ...          ...   
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49997  5 Series  2010    Middle East     Red    Petrol    Automatic   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0                3.5      151748

# Part 3: Classification Evaluation with Confusion Matrix

**Task 5: Dataset-Based Classification Evaluation**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report

In [ ]:
iris = load_iris()

In [ ]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
df['binary_target'] = (df['target'] == 0).astype(int)

In [ ]:
print(df['binary_target'])

0      1
1      1
2      1
3      1
4      1
      ..
145    0
146    0
147    0
148    0
149    0
Name: binary_target, Length: 150, dtype: int64


In [ ]:
X = df[iris.feature_names]
y = df['binary_target']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       1.00      1.00      1.00        19

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



Accuracy = 1 → Every prediction made by the model is correct.

Precision = 1 → Every time the model predicted a positive class, it was right.

Recall = 1 → The model successfully identified all actual positive cases.

F1-Score = 1 → There's a perfect balance between precision and recall.